# Use postgres/example user/password credentials
version: '3.9'

services:

  pgsql:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: dualzone
      POSTGRES_USER: dualzone
      POSTGRES_DB: dualzone
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass dualzone
    volumes:
      - redis:/data
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=dualzone
      - MINIO_ROOT_PASSWORD=dualzone
      - MINIO_DEFAULT_BUCKETS=dualzone
volumes:
  redis:
  postgres:
  minio_data:
