
name: Update documentation
on:
  push:
    branches: ['dev', 'prod', 'testing']
  pull_request:
    branches: ['dev', 'prod', 'testing']
jobs:
  api-doc-events:
    uses: ./.github/workflows/underTasks/bump/bump-events.yml
  api-doc-rest:
    uses: ./.github/workflows/underTasks/bump/bump-rest.yml
