name: Update documentation
on:
  workflow_call:
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Generating HTML from my AsyncAPI document
      uses: asyncapi/github-action-for-cli@v3.1.1 # You can use any version you want
      with:
        command: generate
        filepath: docs/asyncapi.yaml
        output: docs/output/events
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: ./docs/output/rest
        spec-file: ./doc/openapi.yaml
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/output

