name: Node.js prod CI
on:
  push:
    branches: ['prod']
  pull_request:
    branches: ['prod']
jobs:
  test:
    uses: ./.github/workflows/underTasks/code/test.yml
  documentation:
    uses: ./.github/workflows/underTasks/documentation/gh-page-doc.yml
